// Marketing seed (swapped in for apps/web/src/mock/seed/mail.ts by vite.capture.config.ts).
// Maya's inbox at Orbit: a customer thread, GitHub + CI notifications, an investor reply, newsletters, billing.
import { ago } from '@/lib/format'
import type { MailFolder, MailThread } from '@/mock/types'

export const mailFolders: MailFolder[] = [
  { id: 'f_inbox', name: 'Inbox', icon: 'inbox' },
  { id: 'f_starred', name: 'Starred', icon: 'star' },
  { id: 'f_sent', name: 'Sent', icon: 'send' },
  { id: 'f_drafts', name: 'Drafts', icon: 'note' },
  { id: 'f_archive', name: 'Archive', icon: 'archive' },
  { id: 'f_trash', name: 'Trash', icon: 'trash' },
  { id: 'f_customers', name: 'Customers', icon: 'folder', custom: true },
  { id: 'f_investors', name: 'Investors', icon: 'folder', custom: true },
  { id: 'f_hiring', name: 'Hiring', icon: 'folder', custom: true },
]

const pdf = (id: string, fileName: string, fileSize: number) => ({ id, fileName, mimeType: 'application/pdf', fileSize, url: '#' })

export const mailThreads: MailThread[] = [
  {
    id: 'm_1',
    folderId: 'f_inbox',
    subject: 'Moving our team from Notion to Orbit',
    snippet: 'That sounds great. Could we get a 30 minute walkthrough on Thursday? I will bring our ops lead.',
    unread: false,
    starred: true,
    hasAttachment: true,
    updatedAt: ago(38, 'm'),
    messages: [
      {
        id: 'mm_1',
        from: { name: 'Hannah Weiss', email: 'hannah@northwind-labs.com' },
        to: ['maya@orbit.dev'],
        body: 'We are a 40-person hardware startup and currently split between Notion for docs and Jira for tasks. Orbit looks like it could replace both.\n\nTwo questions before we trial it: can we bring our Notion wiki over, and do you support SSO?\n\nBest,\nHannah',
        createdAt: ago(1, 'd'),
      },
      {
        id: 'mm_2',
        from: { name: 'Maya Chen', email: 'maya@orbit.dev' },
        to: ['hannah@northwind-labs.com'],
        body: 'Great to hear from you, Hannah! Yes to both: Notion import ships next week (pages, images and files come across), and SSO via OIDC is available on every plan.\n\nI attached our security overview in case your IT team asks.\n\nMaya',
        createdAt: ago(20, 'h'),
        attachments: [pdf('ma_1', 'orbit-security-overview.pdf', 412_880)],
      },
      {
        id: 'mm_3',
        from: { name: 'Hannah Weiss', email: 'hannah@northwind-labs.com' },
        to: ['maya@orbit.dev'],
        body: 'Thanks, that helps a lot. Our wiki is about 300 pages, mostly engineering notes and onboarding.\n\nHannah',
        createdAt: ago(3, 'h'),
      },
      {
        id: 'mm_4',
        from: { name: 'Hannah Weiss', email: 'hannah@northwind-labs.com' },
        to: ['maya@orbit.dev'],
        body: 'Hi Maya,\n\nWe shared the security overview with IT and they are happy. That sounds great.\n\nCould we get a 30 minute walkthrough on Thursday? I will bring our ops lead, Marco, who would own the migration. We would love to see:\n\n  • the Notion import with a copy of our wiki\n  • how tasks link to docs\n  • roles and permissions for contractors\n\nAny time after 14:00 CET works for us.\n\nThanks,\nHannah Weiss\nHead of Product, Northwind Labs',
        createdAt: ago(38, 'm'),
      },
    ],
  },
  {
    id: 'm_2',
    folderId: 'f_inbox',
    subject: '[orbit-hq/orbit] feat(docs): realtime sync with version checks (PR #412)',
    snippet: '@priya approved these changes. "Nice work, the rebase path is clean."',
    unread: true,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(52, 'm'),
    messages: [
      {
        id: 'mm_5',
        from: { name: 'GitHub', email: 'notifications@github.com' },
        to: ['maya@orbit.dev'],
        body: '@priya approved these changes on pull request #412.\n\n"Nice work, the rebase path is clean. Let us log every rebase for the first week."\n\nView it on GitHub: https://github.com/orbit-hq/orbit/pull/412',
        createdAt: ago(52, 'm'),
      },
    ],
  },
  {
    id: 'm_3',
    folderId: 'f_inbox',
    subject: 'Run failed: CI / e2e (main, a3f9c21)',
    snippet: 'e2e › docs › import-notion.spec.ts failed on attempt 1 of 2 and passed on retry.',
    unread: true,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(2, 'h'),
    messages: [
      {
        id: 'mm_6',
        from: { name: 'GitHub Actions', email: 'noreply@github.com' },
        to: ['maya@orbit.dev'],
        body: 'Run failed: CI / e2e for main (a3f9c21)\n\ne2e › docs › import-notion.spec.ts failed on attempt 1 of 2 and passed on retry.\n\nView workflow run: https://github.com/orbit-hq/orbit/actions/runs/10442871',
        createdAt: ago(2, 'h'),
      },
    ],
  },
  {
    id: 'm_4',
    folderId: 'f_inbox',
    subject: 'Re: Orbit — August investor update',
    snippet: 'Congrats on the docs launch! Two intros below, both teams are drowning in tool sprawl.',
    unread: true,
    starred: true,
    hasAttachment: false,
    updatedAt: ago(4, 'h'),
    messages: [
      {
        id: 'mm_7',
        from: { name: 'Maya Chen', email: 'maya@orbit.dev' },
        to: ['investors@orbit.dev'],
        body: 'Hi all,\n\nAugust highlights: 212 active teams (+38%), Docs launched, net revenue retention at 118%.\n\nMaya',
        createdAt: ago(2, 'd'),
      },
      {
        id: 'mm_8',
        from: { name: 'Daniel Okafor', email: 'daniel@lumen.vc' },
        to: ['maya@orbit.dev'],
        body: 'Congrats on the docs launch! Two intros below, both teams are drowning in tool sprawl.\n\nDaniel',
        createdAt: ago(4, 'h'),
      },
    ],
  },
  {
    id: 'm_5',
    folderId: 'f_inbox',
    subject: 'Your payout of €8,412.60 is on the way',
    snippet: 'Expected to arrive in your bank account on Monday, September 28.',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(6, 'h'),
    messages: [
      {
        id: 'mm_9',
        from: { name: 'Stripe', email: 'notifications@stripe.com' },
        to: ['billing@orbit.dev'],
        body: 'Your payout of €8,412.60 is on the way. Expected to arrive in your bank account on Monday, September 28.',
        createdAt: ago(6, 'h'),
      },
    ],
  },
  {
    id: 'm_6',
    folderId: 'f_inbox',
    subject: 'Application: Senior Frontend Engineer, Jonas Weber',
    snippet: 'Hi Orbit team, I have been using Orbit for our side project and would love to help build it.',
    unread: false,
    starred: false,
    hasAttachment: true,
    updatedAt: ago(9, 'h'),
    messages: [
      {
        id: 'mm_10',
        from: { name: 'Jonas Weber', email: 'jonas.weber@posteo.de' },
        to: ['jobs@orbit.dev'],
        body: 'Hi Orbit team,\n\nI have been using Orbit for our side project and would love to help build it. CV and portfolio attached.\n\nJonas',
        createdAt: ago(9, 'h'),
        attachments: [pdf('ma_2', 'jonas-weber-cv.pdf', 188_210)],
      },
    ],
  },
  {
    id: 'm_7',
    folderId: 'f_inbox',
    subject: 'This Week in Rust 612',
    snippet: 'Hello and welcome to another issue of This Week in Rust! Updates from the Rust community…',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(1, 'd'),
    messages: [
      {
        id: 'mm_11',
        from: { name: 'This Week in Rust', email: 'newsletter@this-week-in-rust.org' },
        to: ['maya@orbit.dev'],
        body: 'Hello and welcome to another issue of This Week in Rust! Updates from the Rust community, crate of the week, and calls for participation.',
        createdAt: ago(1, 'd'),
      },
    ],
  },
  {
    id: 'm_8',
    folderId: 'f_inbox',
    subject: 'Feature request: keyboard shortcut to move tasks',
    snippet: 'Love the new My week view. Would be amazing to move a task to tomorrow with one key.',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(1, 'd'),
    messages: [
      {
        id: 'mm_12',
        from: { name: 'Ravi Shankar', email: 'ravi@pixelfold.io' },
        to: ['feedback@orbit.dev'],
        body: 'Love the new My week view. Would be amazing to move a task to tomorrow with one key.\n\nRavi',
        createdAt: ago(1, 'd'),
      },
    ],
  },
  {
    id: 'm_9',
    folderId: 'f_inbox',
    subject: 'Invoice R-2026-09-1182 for Orbit Cloud',
    snippet: 'Your invoice for September is attached. Payment will be collected automatically.',
    unread: false,
    starred: false,
    hasAttachment: true,
    updatedAt: ago(2, 'd'),
    messages: [
      {
        id: 'mm_13',
        from: { name: 'Hetzner Online', email: 'billing@hetzner.com' },
        to: ['billing@orbit.dev'],
        body: 'Your invoice for September is attached. Payment will be collected automatically.',
        createdAt: ago(2, 'd'),
        attachments: [pdf('ma_3', 'R-2026-09-1182.pdf', 64_300)],
      },
    ],
  },
  {
    id: 'm_10',
    folderId: 'f_sent',
    subject: 'Orbit 0.9 release date',
    snippet: 'Hi everyone, 0.9 with Notion import and realtime docs goes out on Monday.',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(1, 'd'),
    messages: [
      {
        id: 'mm_14',
        from: { name: 'Maya Chen', email: 'maya@orbit.dev' },
        to: ['customers@orbit.dev'],
        body: 'Hi everyone,\n\n0.9 with Notion import and realtime docs goes out on Monday.\n\nMaya',
        createdAt: ago(1, 'd'),
      },
    ],
  },
  {
    id: 'm_11',
    folderId: 'f_drafts',
    subject: 'Orbit — September investor update',
    snippet: 'Draft: September highlights: Notion import, realtime docs, 240 active teams…',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(5, 'h'),
    messages: [
      {
        id: 'mm_15',
        from: { name: 'Maya Chen', email: 'maya@orbit.dev' },
        to: [],
        body: 'September highlights: Notion import, realtime docs, 240 active teams…',
        createdAt: ago(5, 'h'),
      },
    ],
  },
  {
    id: 'm_12',
    folderId: 'f_archive',
    subject: 'Welcome to Orbit Cloud',
    snippet: 'Your workspace is ready.',
    unread: false,
    starred: false,
    hasAttachment: false,
    updatedAt: ago(40, 'd'),
    messages: [
      {
        id: 'mm_16',
        from: { name: 'Orbit', email: 'hello@orbit.dev' },
        to: ['maya@orbit.dev'],
        body: 'Your workspace is ready.',
        createdAt: ago(40, 'd'),
      },
    ],
  },
]
